id: REQ-000
name: AIREF 2024 后端适配 (Master架构)
description: |
  基于 AIREF-master 架构（Django + DRF + PyTorch）适配 2024 版前端。
  核心包含认证、模型评估（ART库）、多进程任务调度及文件管理。
type: infra
children:

  - id: REQ-100
    name: 评估流程模块 (Assess)
    description: |
      支持模型评估流程中的数据上传、预览与测试。
      对应 AIREF-master 的 backend 应用。
    type: infra
    children:
      - id: REQ-101
        name: 基础路由配置
        description: |
          配置根级路由 /data/, /model/, /attack/, /eval/。
          所属模块: Backend
        type: infra
        scenarios:
          - name: 验证路由挂载
            steps:
              - 访问 /data/ 或 /model/ 接口
            expectation:
              - 路由可达

      - id: REQ-102
        name: 实现数据集处理接口
        description: |
          验证数据集有效性。
          所属模块: Backend
          对应接口: POST /data/
        type: feature
        scenarios:
          - name: Happy Path - 数据集验证
            steps:
              - POST /data/ with {data_url: "url", data_token: "token"}
            expectation:
              - HTTP 200
              - 返回数据集预览信息

      - id: REQ-103
        name: 实现模型加载接口
        description: |
          加载并验证模型文件。
          所属模块: Backend
          对应接口: POST /model/
        type: feature
        scenarios:
          - name: Happy Path - 模型加载
            steps:
              - POST /model/ with {model_url: "url", ...}
            expectation:
              - HTTP 200
              - 返回模型结构或验证状态

      - id: REQ-104
        name: 实现攻击效果测试接口
        description: |
          运行攻击测试 (支持 FGM, CW, DEEPFOOL, PGD, PIXEL)。
          所属模块: Backend
          对应接口: POST /attack/ (需实现)
        type: feature
        scenarios:
          - name: Happy Path - 运行攻击
            steps:
              - POST /attack/ with {attack_list: ["FGM"], ...}
            expectation:
              - HTTP 200
              - 返回攻击后图像/结果

  - id: REQ-200
    name: 异步任务系统 (Task)
    description: |
      使用多进程/队列处理耗时攻击任务。
      对应 backend.utils.task 模块。
    type: infra
    children:
      - id: REQ-201
        name: 任务执行引擎
        description: |
          基于 multiprocessing 或 queue 的任务调度。
          支持 adv_black, adv_white 任务类型。
        type: infra
        scenarios:
          - name: 任务提交
            steps:
              - 调用 task_wrapper
            expectation:
              - 任务进入后台执行

      - id: REQ-202
        name: 评估历史记录
        description: |
          记录评估结果供前端查询。
          对应接口: /getEvalHistory/
        type: feature
        scenarios:
          - name: 获取历史
            steps:
              - GET /getEvalHistory/
            expectation:
              - 返回任务列表

  - id: REQ-300
    name: 统计与大屏模块 (Stats)
    description: |
      提供仪表盘所需的统计数据。
    type: infra
    children:
      - id: REQ-301
        name: 实现仪表盘统计接口
        description: |
          聚合历史任务数据返回统计信息。
          (需基于 getEvalHistory 或新增接口实现)
        type: feature
        scenarios:
          - name: Happy Path - 获取统计数据
            steps:
              - GET /api/stats/dashboard (待定)
            expectation:
              - HTTP 200

  - id: REQ-400
    name: 认证与文件模块 (Users)
    description: |
      用户管理与文件操作。
      对应 AIREF-master 的 users 应用。
    type: infra
    children:
      - id: REQ-401
        name: 用户模型 (UserInfo)
        description: |
          扩展 AbstractUser，包含 phone, cate, detail, address。
          所属模块: Users
        type: infra
        scenarios:
          - name: 检查表结构
            steps:
              - 验证 UserInfo 字段
            expectation:
              - 包含自定义字段

      - id: REQ-402
        name: 认证接口
        description: |
          注册、登录、登出。
          对应接口: /auth/register/, /auth/login/, /auth/logout/
        type: feature
        scenarios:
          - name: 登录流程
            steps:
              - POST /auth/login/
            expectation:
              - 返回 token

      - id: REQ-403
        name: 文件管理接口
        description: |
          文件上传与列表管理。
          对应接口: /upload/, /getFolderList/, /getFileList/
        type: feature
        scenarios:
          - name: 文件上传
            steps:
              - POST /upload/
            expectation:
              - 文件保存至 UserData
